[package]
name = "crimson"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.58", features = ["derive"] }
dotenvy = "0.15.7"
postgres = { version = "0.19.12", features = ["with-time-0_3"] }
time = { version = "0.3.47", features = ["macros"] }
